language: csharp

install:

script: 
  - ./autogen.sh  
  - make 
  - sudo make install
  - xbuild ./src/fsharp-library-unittests-build.proj /p:TargetFramework=net40 /p:Configuration=Release
  - nunit-console4 ./lib/release/FSharp.Core.Unittests.dll
  - (cd tests/projects; ./build.sh)
  - (cd tests/fsharp/core; ./run-opt.sh)

